export const SOCKET_EVENTS = {
  JOIN: "join",
  BOARD_SYNC: "board:sync",
  PRIMITIVE_CREATE: "primitive:create",
  PRIMITIVE_CREATED: "primitive:created",
  PRIMITIVE_UPDATE: "primitive:update",
  PRIMITIVE_UPDATED: "primitive:updated",
  PRIMITIVE_DELETE: "primitive:delete",
  PRIMITIVE_DELETED: "primitive:deleted",
  CURSOR_MOVE: "cursor:move",
  CURSOR_MOVED: "cursor:moved",
  USER_RENAME: "user:rename",
  USER_UPDATE: "user:update",
  USER_UPDATED: "user:updated",
  USER_JOINED: "user:joined",
  USER_LEFT: "user:left",
  USER_RENAMED: "user:renamed",
  UNDO: "undo",
  REDO: "redo",
} as const;
